// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAeu5RqUdk8AlH7aZkBaX9mMkMU42sdmE',
    appId: '1:1052770902003:android:d9109cd89031bf36c53c86',
    messagingSenderId: '1052770902003',
    projectId: 'jyotishee-f390d',
    storageBucket: 'jyotishee-f390d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATk485ppqyaM6E97J0mnOSne_btywsc8U',
    appId: '1:1052770902003:ios:5d8f01947d258e5fc53c86',
    messagingSenderId: '1052770902003',
    projectId: 'jyotishee-f390d',
    storageBucket: 'jyotishee-f390d.appspot.com',
    iosBundleId: 'com.snaplor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATk485ppqyaM6E97J0mnOSne_btywsc8U',
    appId: '1:1052770902003:ios:dcbfd79a08cac037c53c86',
    messagingSenderId: '1052770902003',
    projectId: 'jyotishee-f390d',
    storageBucket: 'jyotishee-f390d.appspot.com',
    iosClientId: '1052770902003-hojlbihq6p1vp86q26uii476h9dhc2fq.apps.googleusercontent.com',
    iosBundleId: 'com.jyotishee.jyotishee.RunnerTests',
  );
}
