import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import '../utils.dart';

class AppStyle {
  static TextStyle get white12 => GoogleFonts.poppins(fontSize: 12,color: AppColors.white);
  static TextStyle get white12w500 => GoogleFonts.poppins(fontSize: 12,color: AppColors.white,fontWeight: FontWeight.w500);
  static TextStyle get black12 => GoogleFonts.poppins(fontSize: 12,color: AppColors.black,fontWeight: FontWeight.w500);
  static TextStyle get black10 => GoogleFonts.poppins(fontSize: 10,color: AppColors.black,fontWeight: FontWeight.w500);
  static TextStyle get white10 => GoogleFonts.poppins(fontSize: 10,color: AppColors.white,fontWeight: FontWeight.w500);
  static TextStyle get black12w700 => GoogleFonts.poppins(fontSize: 12,color: AppColors.black,fontWeight: FontWeight.w700);
  static TextStyle get black12w600 => GoogleFonts.poppins(fontSize: 12,color: AppColors.black,fontWeight: FontWeight.w600);
  static TextStyle get hintGray12 => GoogleFonts.poppins(fontSize: 12,color: AppColors.hintGrey2,fontWeight: FontWeight.w500);
  static TextStyle get black10Bold => GoogleFonts.poppins(fontSize: 10,color: AppColors.black,fontWeight: FontWeight.bold);
  static TextStyle get black10w400 => GoogleFonts.poppins(fontSize: 10,color: AppColors.black,fontWeight: FontWeight.w400);
  static TextStyle get black8w400 => GoogleFonts.poppins(fontSize: 8,color: AppColors.black,fontWeight: FontWeight.w400);
  static TextStyle get red12 => GoogleFonts.poppins(fontSize: 12,color: AppColors.red,fontWeight: FontWeight.w500);
  static TextStyle get red12w400 => GoogleFonts.poppins(fontSize: 12,color: AppColors.red,fontWeight: FontWeight.w400);
  static TextStyle get black12w400 => GoogleFonts.poppins(fontSize: 12,color: AppColors.black,fontWeight: FontWeight.w400);
  static TextStyle get lightGreen12 => GoogleFonts.poppins(fontSize: 12,color: AppColors.lightGreen,fontWeight: FontWeight.w500);
  static TextStyle get black12Underline => GoogleFonts.poppins(fontSize: 12,color: AppColors.black,fontWeight: FontWeight.w500,decoration: TextDecoration.underline);
  static TextStyle get primary12 => GoogleFonts.poppins(fontSize: 12,color: AppColors.colorPrimary,fontWeight: FontWeight.w500);
  static TextStyle get black30W700 => GoogleFonts.poppins(fontSize: 30,color: AppColors.black,fontWeight: FontWeight.w700);
  static TextStyle get white14 => GoogleFonts.poppins(fontSize: 14,color: AppColors.white,fontWeight: FontWeight.w500);
  static TextStyle get white14W400 => GoogleFonts.poppins(fontSize: 14,color: AppColors.white,fontWeight: FontWeight.w400);
  static TextStyle get white50 => GoogleFonts.poppins(fontSize: 50,color: AppColors.white,fontWeight: FontWeight.w600);
  static TextStyle get purple14 => GoogleFonts.poppins(fontSize: 14,color: AppColors.colorPrimary,fontWeight: FontWeight.w500);
  static TextStyle get purple40Bold => GoogleFonts.poppins(fontSize: 40,color: AppColors.colorPrimary,fontWeight: FontWeight.bold);
  static TextStyle get hintGray14 => GoogleFonts.poppins(fontSize: 14,color: AppColors.colorPrimary,fontWeight: FontWeight.w500);
  static TextStyle get purple30Bold => GoogleFonts.poppins(fontSize: 30,color: AppColors.colorPrimary,fontWeight: FontWeight.bold);
  static TextStyle get purple14w800 => GoogleFonts.poppins(fontSize: 14,color: AppColors.colorPrimary,fontWeight: FontWeight.w800);
  static TextStyle get purple25Bold => GoogleFonts.poppins(fontSize: 25, fontWeight: FontWeight.bold,color: AppColors.colorPrimary);
  static TextStyle get purple14w600 => GoogleFonts.poppins(fontSize: 14,color: AppColors.colorPrimary,fontWeight: FontWeight.w600);
  static TextStyle get purple18w600 => GoogleFonts.poppins(fontSize: 18,color: AppColors.colorPrimary,fontWeight: FontWeight.w600);
  static TextStyle get purple12 => GoogleFonts.poppins(fontSize: 12,color: AppColors.colorPrimary,fontWeight: FontWeight.w500);
  static TextStyle get purple12w400 => GoogleFonts.poppins(fontSize: 12,color: AppColors.colorPrimary,fontWeight: FontWeight.w400);
  static TextStyle get white16 => GoogleFonts.poppins(fontSize: 16,color: AppColors.white);
  static TextStyle get black22 => GoogleFonts.poppins(fontSize: 22,color: AppColors.black);
  static TextStyle get white26Nova => GoogleFonts.poppins(fontSize: 26,color: AppColors.white,);
  static TextStyle get white26Bold => GoogleFonts.poppins(fontSize: 26,color: AppColors.white,fontWeight: FontWeight.bold);
  static TextStyle get white18Bold => GoogleFonts.poppins(fontSize: 18,color: AppColors.white,fontWeight: FontWeight.bold);
  static TextStyle get grey14 => GoogleFonts.poppins(fontSize: 14,color: AppColors.hintGrey,fontWeight: FontWeight.w400);
  static TextStyle get grey16 => GoogleFonts.poppins(fontSize: 16,color: AppColors.hintGrey);
  static TextStyle get grey12 => GoogleFonts.poppins(fontSize: 12,color: AppColors.hintGrey);
  static TextStyle get greyHint12 => GoogleFonts.poppins(fontSize: 12,color: AppColors.hintGrey2);
  static TextStyle get greyHint14w500 => GoogleFonts.poppins(fontSize: 14,color: AppColors.hintGrey1,fontWeight: FontWeight.w500);
  static TextStyle get grayDark12 => GoogleFonts.poppins(fontSize: 12,color: AppColors.greyDark);
  static TextStyle get grayDark10 => GoogleFonts.poppins(fontSize: 10,color: AppColors.greyDark);
  static TextStyle get grey10w400 => GoogleFonts.poppins(fontSize: 10,color: AppColors.hintGrey1,fontWeight: FontWeight.w400);
  static TextStyle get black18 => GoogleFonts.poppins(fontSize: 18,color: AppColors.black,);
  static TextStyle get black20 => GoogleFonts.poppins(fontSize: 20,color: AppColors.black,);
  static TextStyle get black18Nova => GoogleFonts.poppins(fontSize: 18,color: AppColors.black,);
  static TextStyle get black16 => GoogleFonts.poppins(fontSize: 16,color: AppColors.black);
  static TextStyle get black16w500 => GoogleFonts.poppins(fontSize: 16,color: AppColors.black,fontWeight: FontWeight.w500);
  static TextStyle get lightGreen16 => GoogleFonts.poppins(fontSize: 16,color: AppColors.lightGreen,fontWeight: FontWeight.w500);
  static TextStyle get redMain16 => GoogleFonts.poppins(fontSize: 16,color: AppColors.red,fontWeight: FontWeight.w500);
  static TextStyle get black16Bold => GoogleFonts.poppins(fontSize: 16,color: AppColors.black,fontWeight: FontWeight.bold);
  static TextStyle get black14Bold => GoogleFonts.poppins(fontSize: 14,color: AppColors.black,fontWeight: FontWeight.bold);
  static TextStyle get red16 => GoogleFonts.poppins(fontSize: 16,color: AppColors.redFF0000,);
  static TextStyle get blue16 => GoogleFonts.poppins(fontSize: 16,color: AppColors.colorPrimary,);
  static TextStyle get blue16Bold => GoogleFonts.poppins(fontSize: 16,color: AppColors.colorPrimary,fontWeight: FontWeight.bold);
  static TextStyle get blue12 => GoogleFonts.poppins(fontSize: 12,color: AppColors.colorPrimary);
  static TextStyle get black14 => GoogleFonts.poppins(fontSize: 14,color: AppColors.black,fontWeight: FontWeight.w500);
  static TextStyle get black14Underline => GoogleFonts.poppins(fontSize: 14,color: AppColors.black,fontWeight: FontWeight.w500,decoration: TextDecoration.underline,);
  static TextStyle get black14w600 => GoogleFonts.poppins(fontSize: 14,color: AppColors.black,fontWeight: FontWeight.w600);
  static TextStyle get blackBold24 => GoogleFonts.poppins(fontSize: 24,color: AppColors.black,fontWeight: FontWeight.bold);
  static TextStyle get blackBold26 => GoogleFonts.poppins(fontSize: 26,color: AppColors.black,fontWeight: FontWeight.bold);
  static TextStyle get blueBold26 => GoogleFonts.poppins(fontSize: 26,color: AppColors.colorPrimary,fontWeight: FontWeight.bold);
  static TextStyle get whiteBold20 => GoogleFonts.poppins(fontSize: 20,color: AppColors.white,fontWeight: FontWeight.bold);
  static TextStyle get whiteBold16 => GoogleFonts.poppins(fontSize: 16,color: AppColors.white,fontWeight: FontWeight.bold,);

}
